# Buffs mobs on harder difficulties, adds damage indecators, adds the bloodLustCard integration
on damage:
	if {inGame::%attacker%} is true:
		bloodLustCard(attacker)
		if returnSetting(attacker, "damageIndicator") is 1:
			spawnIndicator(attacker, location of victim, damage, health of victim, max health of victim)
	if {inGame::%victim%} is true:
		if attacker is set:
			set the damage to round(damage * (({difficulty::%{_p}%} - 2) * {difficultyMultiplier}))
