on death of player:
	if state(victim) is 1:
		cancel event
		if secondLife(victim) is false:
			setState(victim, 2)
			deleteRun(returnWorldID(victim))
			set victim's gamemode to spectator
			showDeathScreen(victim)
			wait 5 seconds
			kill victim
			if {currentGameStats::%victim%::misc::extracted} is not true:
				set {currentGameStats::%victim%::misc::extracted} to false
			endGame(victim)
	if state(victim) is 2:
		set death message to deathMsg(victim, "%attacker%")


# Once the player right clicks the beacon they gain invulnerability and gain a 1.2x point bonus to their current points.
# after 6 seconds endGame() runs
on right click on beacon:
	if state(player) is 1:
		cancel event
		playSoundRaw(player, "ui.toast.challenge_complete")
		setState(player, 3)
		deleteRun(returnWorldID(player))
		set {currentGameStats::%player%::misc::extracted} to true
		add {currentGameStats::%player%::points::pointsSpent} to {currentGameStats::%player%::points::points}
		send " " to player
		send "<b><gradient:#52F361:#02CEF6:#52F361>Extracting You Now good job %player%. Heres a Bonus For Your Efforts: %{currentGameStats::%player%::points::pointsSpent} ? 0%</gradient></b>" to player
		send " " to player
		wait 6 seconds
		addBoosterPack(player, 1)
		playDing(player)
		endGame(player)

		log("%player% has extracted")


command /endGame:
	aliases: /stopgame, /endrun, /finish, /leave
	cooldown: 2 seconds
	trigger:
		if state(player) is 1: 
			kill player
		else:
			send "%{color::error}%Error: you are not in a run" to player


function showDeathScreen(p: player):
	set {_val} to a random integer between 1 and (size of {deathTitle::*})
	send title "<#AC0C26>%{deathTitle::%{_val}%}%" to {_p}


function deathMsg(p: player, k: text) :: text:
	set {_msg} to a random element in {deathMsg::*}
	replace all "[player]" with "%{_p}%" in {_msg}
	replace all "[points]" with "%{currentGameStats::%{_p}%::points::points} ? 0%" in {_msg}
	replace all "[killer]" with "%{_k}%" in {_msg}
	replace all "[ranItem]" with "%random element of all available itemTypes%" in {_msg}
	return "%{color::death}%☠ " + {_msg}


function endGame(p: player) :: boolean:
	# Send completion message to all players and player
	endMsg({_p})

	# Saves all player data in the current run to .yaml files
	saveDataToFile({_p})

	# Deletes all variable enchants/armor/ect
	deletePlayerVariables({_p})

	# Disables the depth meter of the player
	if fastboard of {_p} is on:
		toggle {_p}'s fastboard

	# Sets the state of the player to be in the lobby
	setState({_p}, 0)

	# Resets players attributes added from boostercards
	resetAttributes({_p})

	# Endgame has already passed
	return true


function deletePlayerVariables(p: player):
	delete {difficulty::%{_p}%}
	delete {pickaxe::tier::%{_p}%}
	delete {sword::tier::%{_p}%}
	delete {armor::tier::%{_p}%}
	delete {enchantTier::%{_p}%::*}
	delete {customEnchantTier::%{_p}%::*}
	remove {_p} from {pointBar::%{_p}%}
	delete {pointBar::%{_p}%}
	delete {streak::value::%{_P}%}
	delete {enchantCostMultiplier::%{_p}%::*}
	delete {secondLifeUsed::%{_p}%}
	delete {spawnLocation::%{_p}%}


function endMsg(p: player):
	loop all players:
		if loop-player is not {_p}:
			send " %{color::leaderboardTitle}%ⓘ %{_p}% has finished a run with a grand total of %{currentGameStats::%{_p}%::points::points}% points!" to loop-player
	send " " to {_p}
	send " %{color::leaderboardTitle}%Good job on completeing your run please wait a couple minutes for your run to be shown once it is available view it using this link <u>https://stats.notamelon.com/run/%{runCounter}%</u>." to {_p}
	send " " to {_p}
	playDing({_p})