command /leaderboard:
	trigger:
		close the inventory of the player
		send " " to player
		send "<color:#00FF83><b>Visit: <color:#00FFEA><u><b>https://stats.notamelon.com/leaderboard</u><color:#00FF83><b> to see all leaderboard entrees and specific runs!" to player
		send " " to player
		playDing(player)

command /fly:
	permission: op
	trigger:
		if player cannot fly:
			make player fly
		else:
			make player stop flying

command /rename [<text>]:
	permission: mineRush.admin
	trigger:
		set name of player's tool to arg-1
		send "Name set to: %arg-1%" to player

command /setstate [<integer>]:
	permission: mineRush.admin
	trigger:
		setState(player, arg-1)
		send "state set to: %arg-1%" to player
on tab complete of "/setstate":
	set tab completion to "1" and "2" and "3" and "4" and "5"

command /setdifficulty [<number>]:
	permission: mineRush.admin
	trigger:
		set {difficulty::%player%} to arg-1
		send "Difficulty set to: %arg-1%" to player
on tab complete of "/setdifficulty":
	set tab completion to "1" and "2" and "3" and "4" and "5" and "6"

command /givelootbox [<text>]:
	permission: mineRush.admin
	trigger:
		loop 16 times:
			give player {lootBox::item::%arg-1%}
on tab complete of "/givelootbox":
	set tab completion to "common" and "rare" and "legendary"

command /MRdebug [<boolean>]:
	permission: mineRush.admin
	trigger:
		if arg-1 is not set:
			swapBoolean({debugMode::%player%})
		else:
			set {debugMode::%player%} to arg-1
		send "Debug mode: %arg-1%" to player
on tab complete of "/MRdebug":
	set tab completion to "true" and "false"


command /setup:
	permission: mineRush.admin
	trigger:
		setGamerules(world("world"))
		send "%{color::desc}%Run /setspawn" to player

command /ping:
	trigger:
		send "%player's ping%ms" to player


function convertToRoman(num: integer) :: text:
    set {_roman} to ""

    set {_map::*} to "1000=M", and "900=CM", and "500=D", and "400=CD", and "100=C", and "90=XC", and "50=L", and "40=XL", and "10=X", and "9=IX", and "5=V", and "4=IV", and "1=I"

    loop {_map::*}:
        set {_parts::*} to loop-value split at "="
        set {_value} to {_parts::1} parsed as integer
        set {_symbol} to {_parts::2}

        set {_count} to floor({_num} / {_value})
        loop {_count} times:
            set {_roman} to "%{_roman}%%{_symbol}%"

        set {_num} to mod({_num}, {_value})

    return {_roman}


function swapBoolean(v: boolean) :: boolean:
	if {_v} is true:
		return false
	else:
		return true


function swapBooleanNum(v: integer) :: number:
	if {_v} is 1:
		return 0
	else:
		return 1


command /printyamlcache:
	permission: op
	trigger:
		send "%currently loaded yaml files%" to player


function returnTutorialMsg(italic: boolean = false) :: texts:
	set {_text::*} to {tutorialMsg} split at "|"
	if {_italic} is true:
		loop {_text::*}:
			set {_text::%loop-index%} to "<!i>%{color::tutorial}%" + {_text::%loop-index%}
	else:
		loop {_text::*}:
			set {_text::%loop-index%} to "%{color::tutorial}%" + {_text::%loop-index%}
	return {_text::*}


command /feed:
	permission: op
	trigger:
		feed player

command /heal:
	permission: op
	trigger:
		heal player

command /god:
	permission: op
	trigger:
		if player is invulnerable:
			make player vulnerable
		else:
			make player invulnerable



command /tpsmonitor:
	permission: op
	trigger:
		if {tpsMonitor} is true:
			set {tpsMonitor} to false
		else:
			set {tpsMonitor} to true
		while {tpsMonitor} is true:
			send "%average tick time%" to player
			wait 0.5 seconds


command /spec [<player>]:
	cooldown: 15 seconds
	cooldown message: %{color::error}%Please wait %remaining time% before spectating another player.
	cooldown storage: {spectateCooldown::%player%}
	cooldown bypass: op
	usage: %{color::error}%Please select a player from the list, if there are none then there are no players in a run
	trigger:
		if state(player) is 1:
			send "%{color::error}%You cannot spectate a player while in a run" to player
			playErrorSound(player)
			delete {spectateCooldown::%player%}
			stop
		if state(arg-1) is not 1:
			send "%{color::error}%That player is not currently in a run" to player
			playErrorSound(player)
			delete {spectateCooldown::%player%}
			stop

		log("%player% began spectating %arg-1%")

		send "%{color::desc}%Now spectating %arg-1%" to player
		set gamemode of player to spectator
		set {spectating::%player%} to arg-1
		wait 1 second
		set spectator target of player to arg-1

on tab complete of "/spectate":
	loop all players:
		if state(loop-player) is 1:
			add "%loop-player%" to {_players::*}
	set tab completion to {_players}

on player stop spectating:
	if {spectating::%player%} is set:
		log("%player% stopped spectating %{spectating::%player%}%")
		teleport player to {lobbySpawnLoc}
		set gamemode of player to adventure
		wait 1 tick
		delete {spectating::%player%}

on start spectating:
	if {spectating::%player%} is not set:
		send "no"
		cancel event


command /debug:
	permission: admin
	trigger:
		send "Player summary:" to player
		loop {state::*}:
			send "%loop-index%: %loop-value%" to player
		send "There are %size of {worldArray::*}%/%{maxWorlds}% world's. There are %{genServerWorldAmount}% worlds on the gen server" to player
		send "Next RunID: %retNextRunID()%" to player


on command:
	if state(player) is 5:
		send "%{color::error}%You cannot use any commands while spectating" to player
		playErrorSound(player)
		cancel event
	if state(player) is 4:
		if command is not "exit":
			send "%{color::error}%You cannot use most commands while in buildermode please use /exit to leave" to player
			playErrorSound(player)
			cancel event



command /fix [<player>]:
	permission: op
	trigger:
		if arg-1 is not set:
			repair the player's tool
		else:
			repair arg-1's tool

command /entity:
	permission: op
	trigger:
		send health of target entity to player