function saveDataToFile(p: player) :: boolean:
	if {debugMode::%{_p}%} is true:
		delete {currentGameStats::%{_p}%::*}
		exit
	set {_ID} to 0
	load yaml "mineRushData/playerData/%{_p}'s uuid%/gameData.yaml" as "file"
	load yaml "mineRushData/playerData/%{_p}'s uuid%/stats.yaml" as "stats"
	set {_completed} to false
	while {_completed} is false:
		add 1 to {_ID}
		if yaml path "%{_ID}%" in "file" has a value:
			continue
		set {_completed} to true

	# General Stats
	loop {currentGameStats::%{_p}%::blocks::*}:
		set yaml value "%{_ID}%.blocks.%loop-index%" from "file" to loop-value
	loop {currentGameStats::%{_p}%::ores::*}:
		set yaml value "%{_ID}%.ores.%loop-index%" from "file" to loop-value
	loop {currentGameStats::%{_p}%::lootboxes::*}:
		set yaml value "%{_ID}%.lootboxes.%loop-index%" from "file" to loop-value
	loop {currentGameStats::%{_p}%::points::*}:
		set yaml value "%{_ID}%.points.%loop-index%" from "file" to loop-value
	loop {currentGameStats::%{_p}%::misc::*}:
		set yaml value "%{_ID}%.misc.%loop-index%" from "file" to loop-value
	loop {currentGameStats::%{_p}%::shop::*}:
		set yaml value "%{_ID}%.shop.%loop-index%" from "file" to loop-value

	# Time, extractions, and total games played
	set yaml value "%{_ID}%.misc.duration" from "file" to "%difference between now and {currentGameStats::%{_p}%::misc::duration}%"
	set yaml value "%{_ID}%.misc.timePlayed" from "file" to "%now%"
	set yaml value "misc.name" from "stats" to "%{_p}'s name%"

	set yaml value "%{_ID}%.misc.booster" from "file" to "%uncolored name of {card::%retActiveCard({_p})%}% %retCardLevel({_p}, retActiveCard({_p}))%"

	save yaml "file"
	save yaml "stats"
	unload yaml "file"
	unload yaml "stats"

	if {topPoints} < {currentGameStats::%{_p}%::points::points}:
		set {topPoints} to {currentGameStats::%{_p}%::points::points}
		set {topPlayer} to {_p}
	delete {currentGameStats::%{_p}%::*}